### ISSUE TITLE
Delivery Feedback

### ISSUE THREAD

**Issue by vilunov** [DrompiX/wishlist_bot#2]
1. Токен лучше все-таки в конфигах, не надо одновременно конфиги и энвы юзать. Можно переопределять поля в конфигах через энв.
2. тесты
3. Конфиги даже для теста лучше не хранить в `application.conf` внутри проекта. Можно хранить конфиги для тестов в папочке в репе, главное чтобы они не попадали в ресурсы после билда
4. Раз ты заюзал акку, то и бекенд для sttp лучше заюзать акковский, и уж тем более не создавать бекенд как глобальное значение.
5. Слишком много кода в одном месте, надо бы как-то разнести
6. Не надо держать объекты акторов внутри объявления трейта. Тебе там реально нужно, чтобы они зависели от полей трейта и имплементящих его классов?
7. Не надо делать глобальный клиент к БД.
8. И постарайся не юзать глобальный ExecutionContext, а юзать dispatcher из актор-системы.

**Comment by DrompiX** [comment]
3. Как это сделать?
4. Взял из репы телеграм бота. Почему так нельзя?
6. Они зависят оба от Command[Future] и, как мне кажется, идейно явлются частью этого трейта
7. А как делать правильно? В чём проблема с глобальным?

**Comment by FireFoxIL** [comment]
3. Использовать передачу секретов (паролей от бд), через env. Это нужно тупо из соображений безопасности (секреты существуют только в рантайме). Можно идти дальше и передавать hostname, port и прочее, для банального удобство, чтобы каждый раз не пересобирать приложение
4. Просто акковский клиент производительнее  
5. Так можно говорить и до поры, когда файл начинает разрастаться до 1000 строк. Это же банально ухудшает читаемость. Нам при проверке это сильно бросилось в глаза. Зависимость от трейта не является аргументом, есть вот [это](https://docs.scala-lang.org/tour/self-types.html) и ты про этот механизм должен быть в курсе. Но в целом такое выражение зависимостей называется cake-pattern'ом, который сейчас известен как cake-antipattern

**Comment by vilunov** [comment]
Что происходит когда мы кладём объявления классов или трейтов в другой трейт:
```scala
package demo

trait Outer { outer =>
  def a: Int = 100
  class Inner { inner =>
    val a: Int = outer.a
  }
}

class First extends Outer {
  override val a = 10
}

class Second extends Outer {
  override val a = 15
}

object Main extends App {
  val i1 = new First
  val i2 = new Second
  val i3 = new Second
  val j1: i1.Inner = new i1.Inner
  val j2: i2.Inner = new i2.Inner
  val j3: i3.Inner = new i3.Inner
  val k1: Outer#Inner = j2
  //val k2: i2.Inner = j3  // oshibka
  println(j1.a)
  println(j2.a)
  println(j3.a)
}
```

Значения `j1`, `j2` и `j3` принадлежат к трём разным типам, каждый из которых является наследником типа `Outer#Inner`. Ещё каждый из `j1`, `j2` и `j3` внутри себя неявно содержит референс на внешний класс и может пользоваться его полями

**Comment by vilunov** [comment]
С объектами можно аналогичное провернуть если что:
```scala
trait Outer { outer =>
  def a: Int = 100
  object Inner { inner =>
    val a: Int = outer.a
  }
}

class First extends Outer {
  override val a = 10
}

class Second extends Outer {
  override val a = 15
}

object Main extends App {
  val i1 = new First
  val i2 = new Second
  val i3 = new Second
  val j1: i1.Inner.type = i1.Inner
  val j2: i2.Inner.type = i2.Inner
  val j3: i3.Inner.type = i3.Inner
//  val k2: i2.Inner.type = j3  // oshibka
  println(j1.a)
  println(j2.a)
  println(j3.a)
}
```

**Comment by DrompiX** [comment]
3. Так использовать конфиг или env в итоге? Никита же сказал что-то одно. 
5. Я так и не понял, как использовать то что вы скинули, чтобы переделать. Как это поможет вынести воркера и брокера?
6. А с этим что?

**Comment by vilunov** [comment]
3. Конфиг. Если очень хочется энв, то всё равно конфиг, потому что поля в конфиге можно переопределять через параметры запуска.
4. У тебя две версии sttp почему-то используются. `com.softwaremill.sttp` это `1.*`, `sttp` это `2.*`
6. Вынеси объявление объекта из класса/трейта
